//! Single-crate `sql-server` template emitter (Shape B, SHAP-B-01).
//!
//! Mirrors [`crate::templates::workspace`]: one `generate` orchestrator that
//! calls one private `generate_<file>` fn per output file, each a single raw
//! `fs::write(dir.join("X"), <literal>).context(...)`. There is NO template
//! engine — emission is raw string literals (`format!` escapes literal braces as
//! `{{`/`}}`).
//!
//! It emits FOUR files into a SINGLE crate directory (not a workspace):
//! - `Cargo.toml` — pins `pmcp-server-toolkit` with `features = ["code-mode",
//!   "sqlite", "http"]` (D-02/D-06 + the `http` forward for `StreamableHttpServer`).
//! - `src/main.rs` — the Plan 02 Shape C wiring, byte-identical modulo the
//!   example's `PMCP_ASSETS_DIR` harness line (dropped here — H1: the scaffold's
//!   assets are cwd-local for `cargo run`, and on Lambda the deploy bundle puts
//!   them under `/var/task/assets/` where `pmcp::assets` already resolves, so the
//!   SAME `main.rs` runs locally AND on Lambda).
//! - `config.toml` — `[code_mode] enabled = true` with an inline DEV
//!   `token_secret` + `allow_inline_token_secret_for_dev = true` (D-06).
//! - `schema.sql` — idempotent (`CREATE TABLE IF NOT EXISTS` / `INSERT OR
//!   IGNORE`) so a second `cargo run` against a persisted `demo.db` succeeds (H2).

use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::Path;

/// Emit the files of a single runnable `sql-server` crate into `dir`.
///
/// Beyond the four runnable-crate files (`Cargo.toml`, `src/main.rs`,
/// `config.toml`, `schema.sql`) this also emits the deploy descriptor
/// (`deploy.toml` + `.pmcp/deploy.toml`) so `cargo pmcp deploy` selects pmcp.run
/// and bundles the assets with the right secret posture (Phase 86 Plan 05).
pub fn generate(dir: &Path, name: &str) -> Result<()> {
    generate_cargo_toml(dir, name)?;
    generate_main_rs(dir)?;
    generate_config_toml(dir, name)?;
    generate_schema_sql(dir)?;
    generate_deploy_toml(dir, name)?;

    if std::env::var("PMCP_QUIET").is_err() {
        println!("  {} Generated SQL server crate files", "✓".green());
    }
    Ok(())
}

fn generate_cargo_toml(dir: &Path, name: &str) -> Result<()> {
    // A6 published-version coupling: these versions track the to-be-published
    // toolkit. Until `pmcp-server-toolkit 0.1.0` lands on crates.io a local
    // `[patch.crates-io]` is needed for `cargo run` against an unpublished build.
    let content = format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
pmcp = {{ version = "2.8.1", features = ["streamable-http"] }}
pmcp-server-toolkit = {{ version = "0.1.0", features = ["code-mode", "sqlite", "http"] }}
clap = {{ version = "4", features = ["derive", "env"] }}
tokio = {{ version = "1", features = ["macros", "rt-multi-thread"] }}
tracing = "0.1"
tracing-subscriber = {{ version = "0.3", features = ["env-filter"] }}
"#,
    );

    fs::write(dir.join("Cargo.toml"), content).context("Failed to create Cargo.toml")?;
    Ok(())
}

/// The emitted `src/main.rs`. This is the Plan 02 Shape C wiring
/// (`crates/pmcp-server-toolkit/examples/sql_server_http.rs`) with the ONLY
/// deviation being the dropped `PMCP_ASSETS_DIR` harness line (and the example's
/// `//!` header / `FIXTURES_DIR` const, which are harness-only). The golden test
/// `emitted_main_matches_example_modulo_setup` enforces that this cannot drift.
fn emitted_main_rs() -> &'static str {
    r#"//! Config-driven SQL MCP server (streamable HTTP).
//!
//! Generated by `cargo pmcp new --kind sql-server`. Reads `config.toml` +
//! `schema.sql` via [`pmcp::assets::load_string`] (cwd locally, `/var/task/assets/`
//! on Lambda) and opens SQLite at [`pmcp_server_toolkit::demo_db_path`]
//! (`/tmp/demo.db` on Lambda). The SAME `main.rs` runs locally AND deploys
//! unchanged (`cargo pmcp deploy`).

use std::net::SocketAddr;
use std::sync::Arc;

use pmcp::server::streamable_http_server::{StreamableHttpServer, StreamableHttpServerConfig};
use pmcp::Server;
use pmcp_server_toolkit::sql::{SqlConnector, SqliteConnector};
use pmcp_server_toolkit::{ServerBuilderExt, ServerConfig, StaticResourceHandler};
use tokio::sync::Mutex;
use tokio::task::JoinHandle;

/// Inline streamable-HTTP serve helper: collapses `with_config` + `start` into
/// one call while inlining the `StreamableHttpServer` body.
async fn serve(server: Server) -> Result<(SocketAddr, JoinHandle<()>), Box<dyn std::error::Error>> {
    let shared = Arc::new(Mutex::new(server));
    let cfg = StreamableHttpServerConfig::default();
    Ok(
        StreamableHttpServer::with_config("127.0.0.1:0".parse()?, shared, cfg)
            .start()
            .await?,
    )
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cfg = ServerConfig::from_toml_strict_validated(&pmcp::assets::load_string("config.toml")?)?;
    let conn = SqliteConnector::open(pmcp_server_toolkit::demo_db_path().as_ref())?; // CONCRETE (H2)
    conn.execute_batch(&pmcp::assets::load_string("schema.sql")?)
        .await?; // bootstrap on concrete
    let conn: Arc<dyn SqlConnector> = Arc::new(conn); // NOW wrap for the builder
    let builder = Server::builder()
        .name(&cfg.server.name)
        .version(&cfg.server.version);
    let builder = builder.try_tools_from_config_with_connector(&cfg, conn.clone())?;
    let builder = builder.try_code_mode_from_config_with_connector(&cfg, conn)?;
    let server = builder
        .resources_arc(Arc::new(StaticResourceHandler::from(&cfg)))
        .build()?;
    let (addr, handle) = serve(server).await?;
    println!("PMCP_SQL_SERVER_ADDR=http://{addr}"); // machine-readable bound addr (M1)
    handle.await?;
    Ok(())
}
"#
}

fn generate_main_rs(dir: &Path) -> Result<()> {
    fs::write(dir.join("src").join("main.rs"), emitted_main_rs())
        .context("Failed to create src/main.rs")?;
    Ok(())
}

fn generate_config_toml(dir: &Path, name: &str) -> Result<()> {
    // Emit ONLY `deny_unknown_fields`-known keys (any typo is a hard parse error
    // at the consumer, T-86-03-03). `allow_writes = false` is the default-deny
    // read-only-leaning demo posture (T-86-03-04).
    let content = format!(
        r#"# Config-driven SQL MCP server. Parses through `from_toml_strict_validated`
# (`#[serde(deny_unknown_fields)]`); every key below is a known toolkit field.
[server]
name = "{name}"
version = "0.1.0"

[database]
# The runtime opens SQLite at `demo_db_path()` (the shared H1 resolver), NOT a
# config `file_path`. `type` declares the dialect intent.
type = "sqlite"

[[database.tables]]
name = "books"

[code_mode]
# code-mode (validate_code / execute_code) is visible on first run.
enabled = true
allow_writes = false
require_limit = true
max_limit = 1000
# DEV ONLY — replace with a secrets ref (token_secret = "env:CODE_MODE_SECRET").
# When you do, ALSO declare it, or `cargo pmcp package save` refuses the config:
#   [[config_slots]]
#   key = "code_mode.token_secret"
#   kind = "secret"
#   name = "CODE_MODE_SECRET"
# for production. The deploy path (cargo pmcp deploy) substitutes a secrets ref
# automatically. The inline literal below is rejected unless the dev flag is set.
token_secret = "dev-only-insecure-secret-min-16-bytes"
allow_inline_token_secret_for_dev = true

[[tools]]
name = "list_books"
description = "List books ordered by title"
sql = "SELECT id, title, author FROM books ORDER BY title LIMIT :limit"

[[tools.parameters]]
name = "limit"
type = "integer"
description = "Maximum number of rows to return"
required = false
default = 20
"#,
    );

    fs::write(dir.join("config.toml"), content).context("Failed to create config.toml")?;
    Ok(())
}

fn generate_schema_sql(dir: &Path) -> Result<()> {
    // Idempotent (H2): CREATE TABLE IF NOT EXISTS + INSERT OR IGNORE so a second
    // `cargo run` against a persisted demo.db succeeds. Seed values are free of
    // embedded ';'.
    let content = r#"-- Idempotent demo schema (H2): CREATE TABLE IF NOT EXISTS + INSERT OR IGNORE
-- so a second run against a persisted demo.db succeeds and leaves exactly the
-- seeded rows.
CREATE TABLE IF NOT EXISTS books (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL
);

INSERT OR IGNORE INTO books (id, title, author) VALUES (1, 'The Rust Programming Language', 'Steve Klabnik and Carol Nichols');
INSERT OR IGNORE INTO books (id, title, author) VALUES (2, 'Programming Rust', 'Jim Blandy and Jason Orendorff');
INSERT OR IGNORE INTO books (id, title, author) VALUES (3, 'Rust for Rustaceans', 'Jon Gjengset');
"#;

    fs::write(dir.join("schema.sql"), content).context("Failed to create schema.sql")?;
    Ok(())
}

/// Emit the deploy descriptor that drives `cargo pmcp deploy` (Phase 86 Plan 05).
///
/// The file is written to BOTH `deploy.toml` (project root — human-visible, the
/// scaffold's canonical descriptor) and `.pmcp/deploy.toml` (the path
/// [`crate::deployment::config::DeployConfig::load`] reads). It is a complete,
/// parseable `DeployConfig` carrying:
///
/// - `target_type = "pmcp-run"` (M3) — `get_target_id` does NOT infer pmcp.run from
///   project shape, so the target MUST be declared here.
/// - `[assets] include = ["config.toml", "schema.sql"]` (H1) so
///   `bundle_assets_if_configured` places them under `assets/` in the zip →
///   `/var/task/assets/` on Lambda, exactly where `pmcp::assets::load_string`
///   resolves.
/// - Comments documenting the Lambda posture: assets under `/var/task/assets/`,
///   the mutable SQLite DB under `/tmp/demo.db` (`/var/task` is read-only), and the
///   `CODE_MODE_SECRET` deploy secret/env that the deploy path substitutes for the
///   inline DEV `token_secret` (H4 — see `BinaryBuilder::bundle_assets_if_configured`,
///   which rewrites the bundled config's `token_secret` to `${CODE_MODE_SECRET}` for
///   config-driven projects so the deployed artifact never ships the dev literal).
fn generate_deploy_toml(dir: &Path, name: &str) -> Result<()> {
    let content = format!(
        r#"# Deploy descriptor for `cargo pmcp deploy` (config-driven single-crate server).
#
# Lambda runtime posture (Phase 86 Plan 05):
# - Assets (config.toml + schema.sql) are bundled under `assets/` and extract to
#   `/var/task/assets/` on Lambda — exactly where `pmcp::assets::load_string`
#   resolves them. `/var/task` is READ-ONLY.
# - The mutable SQLite DB is opened at `/tmp/demo.db` (the only writable path on
#   Lambda) via `pmcp_server_toolkit::demo_db_path()`.
# - SECRET (H4): the local `config.toml` carries an inline DEV `token_secret` for
#   out-of-box `cargo run`. The deploy path substitutes `${{CODE_MODE_SECRET}}`
#   into the BUNDLED config so the deployed artifact NEVER ships the dev literal —
#   supply `CODE_MODE_SECRET` as a deploy secret/env on pmcp.run.

[target]
# M3: pmcp.run is selected by THIS value (get_target_id reads target.type); it is
# NOT inferred from project shape.
type = "pmcp-run"
version = "1.0.0"

[aws]
region = "us-east-1"

[server]
name = "{name}"
memory_mb = 512
timeout_seconds = 30

[environment]
RUST_LOG = "info"

[auth]
enabled = false
provider = "none"

[observability]
log_retention_days = 30
enable_xray = false
create_dashboard = false

[assets]
# H1: bundled under `assets/` → `/var/task/assets/{{config.toml,schema.sql}}` on
# Lambda, where `pmcp::assets::load_string` reads them.
include = ["config.toml", "schema.sql"]
"#,
    );

    fs::write(dir.join("deploy.toml"), &content).context("Failed to create deploy.toml")?;

    // DeployConfig::load reads `<project_root>/.pmcp/deploy.toml`; emit a copy there
    // so `cargo pmcp deploy` (and the Task 3 parse test) load the same descriptor.
    let pmcp_dir = dir.join(".pmcp");
    fs::create_dir_all(&pmcp_dir).context("Failed to create .pmcp directory")?;
    fs::write(pmcp_dir.join("deploy.toml"), &content)
        .context("Failed to create .pmcp/deploy.toml")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The canonical Plan 02 Shape C example. The emitted `src/main.rs` must be
    /// the same wiring modulo (a) the example's `//!` header doc, (b) the
    /// harness-only `FIXTURES_DIR` const + its doc, and (c) the `PMCP_ASSETS_DIR`
    /// setup line inside `main`. This proves Plan 03 cannot drift from Plan 02.
    const EXAMPLE_SRC: &str =
        include_str!("../../../crates/pmcp-server-toolkit/examples/sql_server_http.rs");

    /// Collapse a Rust source to its load-bearing wiring: drop blank lines, `//!`
    /// header docs, `///`/`//` comments, and the harness-only seams (the
    /// `FIXTURES_DIR` const and the `PMCP_ASSETS_DIR` setup line).
    fn wiring_lines(src: &str) -> Vec<String> {
        src.lines()
            .map(|l| {
                // Strip trailing line comments so e.g. "...; // CONCRETE (H2)" and
                // "...?; // bootstrap on concrete" compare equal across files.
                match l.find("//") {
                    Some(idx) => l[..idx].trim_end(),
                    None => l,
                }
                .to_string()
            })
            .filter(|l| {
                let t = l.trim();
                if t.is_empty() {
                    return false;
                }
                if t.starts_with("//") {
                    return false; // doc / line comments (incl. //! header, /// docs)
                }
                if t.starts_with("const FIXTURES_DIR") {
                    return false; // harness-only const (example)
                }
                if t.contains("PMCP_ASSETS_DIR") {
                    return false; // harness-only setup line (example)
                }
                true
            })
            .map(|l| l.trim_end().to_string())
            .collect()
    }

    #[test]
    fn emitted_main_matches_example_modulo_setup() {
        let emitted = wiring_lines(emitted_main_rs());
        let example = wiring_lines(EXAMPLE_SRC);
        assert_eq!(
            emitted, example,
            "emitted src/main.rs wiring drifted from the Plan 02 Shape C example \
             (modulo //! header, FIXTURES_DIR const, and PMCP_ASSETS_DIR line)"
        );
    }

    #[test]
    fn emitted_main_has_h1_h2_wiring_tokens() {
        // Defensive: even if line-by-line comparison were relaxed, these exact
        // wiring tokens must be present (H1 resolver + H2 ordering + serve). The
        // serve() helper sits above main, so `StreamableHttpServer::with_config`
        // is checked for presence, not strict source order.
        let m = emitted_main_rs();
        let tokens = [
            "assets::load_string(\"config.toml\")",
            "demo_db_path()",
            "execute_batch",
            "Arc::new(conn)",
            "try_code_mode_from_config_with_connector",
            "StreamableHttpServer::with_config",
            "PMCP_SQL_SERVER_ADDR",
        ];
        for tok in tokens {
            assert!(
                m.contains(tok),
                "emitted main.rs missing wiring token: {tok}"
            );
        }
        // H2: the assets::load_string("schema.sql") + execute_batch on the
        // concrete connector must precede the Arc<dyn SqlConnector> wrap.
        let batch = m.find("execute_batch").expect("execute_batch present");
        let wrap = m
            .find("let conn: Arc<dyn SqlConnector>")
            .expect("Arc<dyn> wrap present");
        assert!(
            batch < wrap,
            "execute_batch must run before the Arc<dyn> wrap (H2)"
        );
        // H1: the harness-only PMCP_ASSETS_DIR line is dropped in the scaffold.
        assert!(
            !m.contains("PMCP_ASSETS_DIR"),
            "emitted main.rs must NOT set PMCP_ASSETS_DIR (H1 — scaffold assets are cwd-local)"
        );
    }
}
